### ISSUE TITLE
ModuleNotFound error with options test file

### ISSUE THREAD

**Issue by isaranjha** [mcdallas/wallstreet#13]
I've installed wallstreet per the instructions with pip and everything seemed to go fine with no errors, but when I run the test files I get:

`   from wallstreet import wallstreet, blackandscholes
ModuleNotFoundError: No module named 'wallstreet'`

Ideas?

**Comment by deragon** [comment]
I guess you must install the modules on your system first by running the provided `setup.py` script.  As a workaround, I ran:

    export PYTHONPATH="<wallstreet downloaded path>:${PYTHONPATH}"
    python3 test_option.py

However, running this, the following error occurs.  It seams that a file is missing from the repository:

    ImportError: No module named 'wallstreet.constants'; 'wallstreet' is not a package

BTW, I am not a developer of this module, but a simple user as you.  I just wanted to try it, to see if it is still relevant (because APIs on the web change so often these days) and I did not get it working.  I am looking elsewhere now.  It is version 0.2 and not yet ready for out of the box usage I guess.
